awk: (FILENAME=tf.nfkb.bed FNR=702) warning: error writing standard output (Broken pipe)
awk: (FILENAME=gencode.v19.annotation.chr22.transcript.gtf FNR=43) fatal: print to "standard output" failed (Broken pipe)
awk: (FILENAME=gencode.v19.annotation.chr22.transcript.promoter.gtf FNR=95) fatal: print to "standard output" failed (Broken pipe)
awk: (FILENAME=gencode.v19.annotation.chr22.transcript.promoter.nfkb.gtf FNR=83) fatal: print to "standard output" failed (Broken pipe)
awk: (FILENAME=gencode.v19.annotation.chr22.transcript.promoter.nfkb.fasta FNR=142) fatal: print to "standard output" failed (Broken pipe)
